/* eslint-disable import/prefer-default-export */
const data = [
  {
    id: 0,
    title: 'Основы Node.js. Многопоточность. База',
    body: 'Содержимое',
    questions: [
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
    ],
  },
  {
    id: 1,
    title: 'Потоки. Treads.',
    body: 'Содержимое',
    questions: [
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
    ],
  },
  {
    id: 2,
    title: 'RestAPI',
    body: 'Содержимое',
    questions: [
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
    ],
  },
  {
    id: 3,
    title: 'Чтение файлов',
    body: 'Содержимое',
    questions: [
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
    ],
  },
  {
    id: 4,
    title: 'Запись файлов',
    body: 'Содержимое',
    questions: [
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
    ],
  },
  {
    id: 5,
    title: 'Кэширование',
    body: 'Содержимое',
    questions: [
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
    ],
  },
  {
    id: 6,
    title: 'Express.js',
    body: 'Содержимое',
    questions: [
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
    ],
  },
  {
    id: 7,
    title: 'Запрос на сервер',
    body: 'Содержимое',
    questions: [
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
    ],
  },
  {
    id: 8,
    title: 'SQLite',
    body: 'Содержимое',
    questions: [
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
    ],
  },
  {
    id: 9,
    title: 'Bearer Token',
    body: 'Содержимое',
    questions: [
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
    ],
  },
  {
    id: 10,
    title: 'Урок 5',
    body: 'Содержимое',
    questions: [
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
    ],
  },
  {
    id: 11,
    title: 'Урок 6',
    body: 'Содержимое',
    questions: [
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
      { question: 'body of question', type: 'boolean', answer: true },
      { question: 'body of second question', type: 'string', answer: 'string of question' },
    ],
  },
];

export default data;
